version: '3.1'

services:
  mongodb:
    image: mongo
    container_name: lotochecker.db
    restart: always
    ports: 
      - "27017:27017"

  node:
    build: .
    image: lotochecker-api:1.1
    container_name: lotochecker.api
    ports:
      - "8088:3000"
    depends_on: 
      - mongodb
    links:
      - mongodb